### ISSUE TITLE
Voter registration UI bugs

### ISSUE THREAD

**Issue by crieggalder** [andreisarebi/civic-app#80]
Mocks for reference: https://www.figma.com/file/cecPCBc0nhNva7VdTOb2DRqh/Civic-Design?node-id=0%3A1

![b29baa95-1c80-4f80-a5d3-9d0817baf6e9](https://user-images.githubusercontent.com/36721640/46698582-5d119380-cbcc-11e8-9c36-536efa4c7212.png)
"Are you registered..." should be centered, buttons need drop shadow and should be closer together, slightly more space between "Are you registered" and buttons, "No/Not Sure" --> "No / Not Sure"

![24c8548e-dad5-47df-99e2-c9bb4fe53450](https://user-images.githubusercontent.com/36721640/46698592-6438a180-cbcc-11e8-8ea7-42b20ba2dcd3.png)
More space between "Let's get you registered..." and "Registering takes...", button needs drop shadow and should be wider and closer to bottom of screen, image should be aligned so that ballot box is centered rather than centering whole image.

![aaf6e414-4c60-42ae-9cd2-e3d467b30fa7](https://user-images.githubusercontent.com/36721640/46698598-669afb80-cbcc-11e8-9e3f-3ec5bd2974b1.png)
More space between "Congrats!..." and ""We'll remind you...", button glitch should be fixed - same width, height, and position as button on screen above.

**Comment by william-chu** [comment]
@crieggalder Hi Chris, I have just submitted a pr for issue80. See screenshots of what it looks like on my phone after making my changes.

![image](https://user-images.githubusercontent.com/25733358/46775688-18b1f080-ccbd-11e8-8660-f2fb7812242a.png)

![image](https://user-images.githubusercontent.com/25733358/46775921-3895e400-ccbe-11e8-8ae1-48b69a50852b.png)

![image](https://user-images.githubusercontent.com/25733358/46775892-1a2fe880-ccbe-11e8-819f-bd5e9be2c40c.png)

![image](https://user-images.githubusercontent.com/25733358/46775930-42b7e280-ccbe-11e8-8509-96e2864592e3.png)

@vahurtad Hi Vanessa, I noticed there was issue 85 with the activism button wrapping the text. I tried to fix this but noticed you also made a pr. In my pr I added some width changes to that screen's card so that it is the same width as the cards used in the sign up survey.

![image](https://user-images.githubusercontent.com/25733358/46775776-85c58600-ccbd-11e8-9eee-2e6ba960f21c.png)

**Comment by william-chu** [comment]
these changes are now reflected in the merged pr
